version: '3.2'

services:
    pluginVisualServeJs:
        image: synbiohub/plugin-visual-serve-test-js:snapshot
        ports:
            - "8086:5000"
        volumes:
            - type: volume
              source: pluginVisualServeJs
              target: /mnt
        restart: always
        dns: 8.8.8.8
        depends_on:
            - synbiohub

volumes:
    pluginVisualServeJs:
