version: '3.2'

services:
    pluginVisualIgem:
        image: synbiohub/igem-plugin:snapshot
        ports:
            - "3000:3000"
        volumes:
            - type: volume
              source: pluginVisualIgem
              target: /mnt
        dns: 8.8.8.8
        restart: always
        depends_on:
            - synbiohub

volumes:
    pluginVisualIgem:
