version: '3.2'

services:
    pluginDownloadTest:
        image: synbiohub/plugin-download-test:snapshot
        ports:
            - "8089:5000"
        volumes:
            - type: volume
              source: pluginDownloadTest
              target: /mnt
        dns: 8.8.8.8
        restart: always
        depends_on:
            - synbiohub

volumes:
    pluginDownloadTest:
