version: '3.2'

services:
    explorer:
        image: myersresearchgroup/sbolexplorer:snapshot-synbiohub
        ports:
            - "13162:13162"
        depends_on:
            - elasticsearch
            - synbiohub
        dns: 8.8.8.8
        volumes:
            - type: volume
              source: explorer
              target: /mnt
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
        ports:
            - "9200:9200"
        volumes:
            - esdata:/usr/share/elasticsearch/data

volumes:
    esdata:
    explorer:
