
version: '3.2'

services:
    pluginVisualSeqviz:
        image: synbiohub/plugin-visual-sequviz:snapshot
        ports:
            - "8085:5000"
        volumes:
            - type: volume
              source: pluginVisualSeqviz
              target: /mnt
        dns: 8.8.8.8
        restart: always
        depends_on:
            - synbiohub

volumes:
    pluginVisualSeqviz:
