version: '3.2'

services:
    pluginVisualTestJs:
        image: synbiohub/plugin-visual-test-js:snapshot
        ports:
            - "8082:5000"
        volumes:
            - type: volume
              source: pluginVisualTestJs
              target: /mnt
        dns: 8.8.8.8
        restart: always
        depends_on:
            - synbiohub

volumes:
    pluginVisualTestJs:
