version: '3.2'

services:
    autoheal: 
        restart: always
        image: willfarrell/autoheal
        environment: 
            - AUTOHEAL_CONTAINER_LABEL=all
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    explorer:
        image: michael13162/sbolexplorer:snapshot-synbiohub
        ports:
            - "13162:13162"
        depends_on:
            - elasticsearch
            - synbiohub
        dns: 8.8.8.8
        volumes:
            - type: volume
              source: explorer
              target: /mnt
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
        ports:
            - "6200:6200"
        volumes:
            - esdata:/usr/share/elasticsearch/data
    virtuoso:
        build: ./virtuoso
        volumes: 
            - type: volumne
              source: virtuoso-db
              target: /data
        ports:
            - "8890:8890"
        restart: always  
    synbiohub:
        image: synbiohub/synbiohub:1.4.1-standalone
        depends_on: 
            - virtuoso
        ports:
            - "7777:7777"
        volumes:
            - type: volume
              source: sbh
              target: /mnt
        dns: 8.8.8.8
        restart: always

volumes:
    virtuoso-db:
    sbh:
    esdata:
    explorer:
