version: '3.2'

services:
    autoheal: 
        restart: always
        image: willfarrell/autoheal
        environment: 
            - AUTOHEAL_CONTAINER_LABEL=all
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    virtuoso:
        build: ./virtuoso
        volumes: 
            - type: volume
              source: virtuoso-db
              target: /data
        ports:
            - "8890:8890"
        restart: always  
    synbiohub:
        image: synbiohub/synbiohub:1.5.2-standalone
        depends_on: 
            - virtuoso
        ports:
            - "7777:7777"
        volumes:
            - type: volume
              source: sbh
              target: /mnt
            - type: volume
              source: virtuoso-db
              target: /virtuoso
        dns: 8.8.8.8
        restart: always

volumes:
    virtuoso-db:
    sbh:
